### ISSUE TITLE
Elementary OS 5.0 Parental Controls not working (as of Sept. 2019)

### ISSUE THREAD

**Issue by mwoyak** [elementary/switchboard-plug-parental-controls#100] opened 2019-09-18 15:33 UTC
On Sept. 5 I installed Elementary OS 5.0 as a virtual machine using Virtualbox.

While logged in to my administrator user account, I created another standard user account for my son. I wanted to test the parental controls features so I turned them on for his account. Then I proceeded to block google.com (as well as https://www.google.com, and www.google.com) as a test.

I also blocked the App Store, Terminal, and Epiphany browser on his account.

I logged out of myself and logged in to his account.

However, while logged in to his account, I was still able to open and use all three blocked apps and navigate to google.com in the Epiphany browser.

I logged back in to my admin user account and all of the parental control settings were still there, just as I had made them.

I've even shut down and restarted the instance.

I've also updated and upgraded all packages and the OS through the terminal, so everything seems to be running properly.

Anyone have any idea why the parental control feature might not be working...at ALL?

Can anyone duplicate this issue? Or are the parental control settings working for you?

I realize that this was reported previously (back in February?) and that the issues were closed.  But it seems like it is not working again.

Thanks!

**Comment by worldofpeace** [comment] 2019-09-18 21:48
Duplicate of https://github.com/elementary/switchboard-plug-parental-controls/issues/55

**Closed** 2020-04-09 18:49 UTC
