### ISSUE TITLE
Track and display app usage times

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-parental-controls#48] opened 2018-08-08 17:33 UTC
The new digital wellbeing features in iOS and Android both seem to track and display app usage, i.e. time spent in an app in their respective digital wellbeing dashboards. This seems like something that could be useful both for parents to understand their kids' usage, and also combined with #46 to enable personal digital wellbeing to better understand one's own usage.

**Comment by danrabbit** [comment] 2018-08-09 23:43
Duplicate of #44 ;)

**Closed by danrabbit** 2018-08-09 23:43 UTC
